# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic

# Platform
TARGET_BOARD_PLATFORM := mt6580

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := DIGMA

# Kernel
BOARD_KERNEL_CMDLINE := \
	bootopt=64S3,32S1,32S1 \
	androidboot.selinux=permissive
TARGET_PREBUILT_KERNEL := device/digma/PS1185MG/prebuilt/zImage-dtb
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_MKBOOTIMG_ARGS += \
	--ramdisk_offset 0x04000000 \
	--tags_offset 0x0e000000
BOARD_KERNEL_IMAGE_NAME := zImage-dtb

# Partitions
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x1000000
TARGET_USERIMAGES_USE_EXT4 := true

# OTA
TARGET_OTA_ASSERT_DEVICE := PS1185MG

# TWRP
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := false
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_EXCLUDE_MTP := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true